- hosts: terraform-ansible
  tasks:
  - name: criando arquivo
    copy:
      dest: /var/www/html/index.html
      content: <h1>Terraform-Ansible provisioning</h1>
      update_cache: yes
    become: yes